- name: "Add upgrade function: Wait for Karaf to start"
  wait_for: "port={{ karaf_ssh_port }} timeout=30"
  tags:
    - upgrage-function

- name: "Add upgrade function: Add features url"
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:{{ karaf_command_prefix_refresh }} {{ karaf_feature_function_upgrade_url }}/xml/features"'
  sudo: yes
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  tags:
    - upgrage-function

- name: "Add upgrade function: Update features"
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:install {{ karaf_feature_function_upgrade_name }}/{{ karaf_feature_function_upgrade_version }}"'
  sudo: yes
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  tags:
    - upgrage-function