---

- name: "Apply base configuration values"
  lineinfile:
    dest: "{{ karaf_home }}/etc/{{ item.0.file }}"
    state: present
    regexp: "^#?{{ item.1.prop }}.*$"
    line: "{{ item.1.prop }} = {{ item.1.value }}"
  with_subelements:
    - "{{ karaf_base_configuration }}"
    - params
  when: item.1.value is defined and item.1.value != '_UNDEFINED_'
  notify: Karaf configuration changed
  tags:
    - config

- name: "Set custom configuration values"
  set_fact:
    karaf_custom_configuration: |
          {%- set items = [] -%}
          {%- for elem in (hostvars[inventory_hostname] | select('match', 'karaf_custom_configuration.*') | map('extract', hostvars[inventory_hostname]) | list) -%}
              {{ items.extend(elem) }}
          {%- endfor -%}
          {{ items | list }}
  tags:
    - config

- name: "Apply custom configuration values"
  lineinfile:
    dest: "{{ karaf_home }}/etc/{{ item.0.file }}"
    state: present
    regexp: "^#?{{ item.1.prop }}.*$"
    line: "{{ item.1.prop }} = {{ item.1.value }}"
    owner: "{{ karaf_os_user_name }}"
    group: "{{ karaf_os_user_name }}"
    mode: 0644
    create: yes
  with_subelements:
    - "{{ karaf_custom_configuration }}"
    - params
  when: item.1.value is defined and item.1.value != '_UNDEFINED_'
  notify: Karaf configuration changed
  tags:
    - config

- name: "Apply multiline custom configuration values"
  replace:
    dest: "{{ karaf_home }}/etc/{{ item.0.file }}"
    regexp: '^#?[ \t]*{{ item.1.prop }}([ \t\w\d:/@\.=,\-]+(\\\n\r?)?)+'
    replace: "{{ item.1.prop }} = {{ item.1.value }}"
  with_subelements:
    - "{{ karaf_multiline_custom_configuration }}"
    - params
  when: item.1.value is defined and item.1.value != '_UNDEFINED_'
  notify: Karaf configuration changed
  tags:
    - config

- name: 'Configure jre.properties'
  replace:
    dest: "{{ karaf_home }}/etc/jre.properties"
    regexp: '(#?[ \t]*jre-1.[\d\d])([ \t\w\d:/@\.=,\-]+)'
    replace: '\1={{ karaf_jre_properties }}, '
  when: karaf_jre_properties != ''
  notify: Karaf configuration changed
  tags:
    - config

- name: 'Configure custom jre.properties'
  replace:
    dest: "{{ karaf_home }}/etc/jre.properties"
    regexp: '(.*javax.xml.validation).*([ \t\w\d:/@\.=,\-])'
    replace: ' {{ item.prop }};{{ item.value }}, '
  with_items: "{{ karaf_custom_jre_properties }}"
  when: item.value is defined and item.value != '_UNDEFINED_'
  notify: Karaf configuration changed
  tags:
    - config

- name: 'Configure shell'
  lineinfile:
    dest: "{{ karaf_home }}/etc/shell.init.script"
    line: 'feature:restart = { feature:stop $args; feature:start $args; };'
  notify: Karaf configuration changed
  tags:
    - config

- name: 'Configure org.apache.karaf.features.cfg'
  replace:
    dest: "{{ karaf_home }}/etc/org.apache.karaf.features.cfg"
    regexp: '(^#?[ \t]*featuresBoot =)([ \t\w\d:/@\.=,\-]+)'
    replace: '\1 {{ karaf_additional_boot_features }}, '
  when: karaf_additional_boot_features != ''
  notify: Karaf configuration changed
  tags:
    - config
