---

- name: "Unregister Karaf service on Karaf home changed"
  service:
    name: "{{ karaf_service_name }}"
    enabled: no
  become: yes
  when: karaf_os_user_home_changed | bool
  ignore_errors: True
  tags:
    - service

- name: "Configure service user"
  lineinfile:
    dest: "{{ karaf_home }}/bin/{{ karaf_service_link_name }}"
    state: present
    regexp: "^#?RUN_AS_USER.*$"
    line: "RUN_AS_USER={{ karaf_os_user_name }}"
  become: yes
  tags:
    - service

- name: "Create service simlink"
  file:
    src: "{{karaf_home }}/bin/{{ karaf_service_link_name }}"
    dest: "/etc/init.d/{{ karaf_service_name }}"
    state: link
  when: ansible_service_mgr is defined and ansible_service_mgr != 'systemd'
  tags:
   - service

- name: "Patch wrapper systemd unit: Set User"
  lineinfile:
    dest: "{{ karaf_home }}/bin/{{ karaf_service_name }}.service"
    state: present
    regexp: 'User={{ karaf_service_name }}'
    insertafter: 'Type=forking'
    line: 'User={{ karaf_service_name }}'
  when: ansible_service_mgr is defined and ansible_service_mgr == 'systemd'

- name: "Register Karaf service on systemd"
  shell: 'systemctl enable {{ karaf_home }}/bin/{{ karaf_service_name }}.service'
  become: yes
  register: karaf_service_registered_on_systemd
  when: (ansible_service_mgr is defined and ansible_service_mgr == 'systemd' and not karaf_new_install_dir_created.stat.exists)
            or (ansible_service_mgr is defined and ansible_service_mgr == 'systemd' and karaf_os_user_home_changed | bool)
  tags:
   - service

- name: "Register Karaf service"
  service:
    name: "{{ karaf_service_name }}"
    enabled: yes
  become: yes
  register: karaf_service_registered
  when: ansible_service_mgr is defined and ansible_service_mgr != 'systemd'
  tags:
    - service

- name: "Start Karaf service"
  service:
    name: "{{ karaf_service_name }}"
    state: started
  become: yes
  tags:
    - service
