---

- name: "Configure wrapper 1"
  lineinfile:
    dest: "{{karaf_home }}/etc/{{ karaf_service_name }}-wrapper.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ karaf_wrapper_conf1 }}"
  notify: Karaf restart
  tags:
    - config

- name: "Slurp wrapper.conf file"
  shell: 'cat {{karaf_home }}/etc/{{ karaf_service_name }}-wrapper.conf'
  register: karaf_wrapper_slurpfile
  changed_when: false
  tags:
    - config

- name: "Get last numeric on wrapper.java.additional"
  set_fact:
    karaf_wrapper_conf_last_num:
      '{%- set tmp = [] -%}
       {%- for elem in karaf_wrapper_slurpfile.stdout_lines | map("regex_search", "wrapper\.java\.additional\.(\d+).*$") | list -%}
         {%- if elem -%}
           {{ tmp.append(karaf_wrapper_slurpfile.stdout_lines[loop.index - 1].split(".")[3].split("=")[0] | int ) }}
         {%- endif -%}
       {%- endfor -%}
       {{ tmp | last }}'
  tags:
    - config

- name: "Add include ansible-overrides-wrapper.conf"
  lineinfile:
    dest: "{{karaf_home }}/etc/{{ karaf_service_name }}-wrapper.conf"
    line: "#include ../etc/{{ item }}"
  with_items:
    - 'ansible-overrides-wrapper.conf'
    - 'ansible-overrides-jvm-memory.conf'
  tags:
    - config

- name: "Configure wrapper"
  template:
    src: '{{ item }}.j2'
    dest: '{{karaf_home }}/etc/{{ item }}'
    owner: '{{ karaf_os_user_name }}'
    group: '{{ karaf_os_user_name }}'
    mode: 0644
    backup: yes
  with_items:
    - 'ansible-overrides-wrapper.conf'
    - 'ansible-overrides-jvm-memory.conf'
  notify: Karaf restart
  tags:
    - config

- name: "Delete old jvm memory configuration values"
  lineinfile:
    dest: '{{ karaf_home }}/etc/{{ karaf_service_name }}-wrapper.conf'
    state: absent
    regexp: '^#?{{ item }}.*$'
  with_items:
    - 'wrapper.java.initmemory'
    - 'wrapper.java.maxmemory'
  notify: Karaf restart
  tags:
    - config
