---

- name: Configure wrapper 1
  lineinfile:
    dest: "{{karaf_home }}/etc/{{ karaf_service_name }}-wrapper.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: karaf_wrapper_conf1
  notify: Wrapper configuration changed
  tags:
    - config

- name: Configure wrapper 2
  lineinfile:
    dest: "{{karaf_home }}/etc/{{ karaf_service_name }}-wrapper.conf"
    state: present
    insertafter: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: karaf_wrapper_conf2
  notify: Wrapper configuration changed
  tags:
    - config
