---

- name: "Delete Data: Stop Karaf service"
  service:
    name: '{{ karaf_service_name }}'
    state: stopped
  ignore_errors: True
  sudo: yes
  tags:
    - delete-data

- name: "Delete Data: Create directory data-backup"
  file:
    path: '{{ karaf_path_to_data_backup }}'
    state: directory
  tags:
    - delete-data

- name: "Delete Data: move 'data' directory"
  shell: 'mv -f {{ karaf_home }}/data {{ karaf_path_to_data_backup }}/$(date +%F_%T)'
  sudo: yes
  tags:
    - delete-data

- name: "Delete Data: Start Karaf service"
  service:
    name: '{{ karaf_service_name }}'
    state: started
  sudo: yes
  tags:
    - delete-data
