---

- name: "Install feature: Wait for Karaf to start"
  wait_for: "port={{ karaf_ssh_port }} timeout=30"
  tags:
    - install-features

- name: "Upgrade feature: Add features configs"
  sudo: yes
  template:
    src: "{{ karaf_path_features_configs }}{{ '/' ~ karaf_environment_configs if karaf_environment_configs is defined else '' }}/{{ item.1 }}"
    dest: '{{ karaf_home }}/etc/{{ item.1 | regex_replace(".j2", "") }}'
    owner: "{{ karaf_os_user_name }}"
    group: "{{ karaf_os_user_name }}"
    mode: 0644
    backup: yes
  with_subelements:
    - karaf_features
    - conf_files
  tags:
    - install-features

- name: "Upgrade feature: Add external data source"
  sudo: yes
  template:
    src: "{{ karaf_path_features_configs }}{{ '/' ~ karaf_environment_configs if karaf_environment_configs is defined else '' }}/{{ item.1 }}"
    dest: '{{ karaf_home }}/deploy/{{ item.1 | regex_replace(".j2", "") }}'
    owner: "{{ karaf_os_user_name }}"
    group: "{{ karaf_os_user_name }}"
    mode: 0644
    backup: yes
  with_subelements:
    - karaf_features
    - data_source_files
  tags:
    - install-features

- name: "Install feature: Add features url"
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:{{ karaf_command_prefix_refresh }} {{ item.url }}/xml/features"'
  changed_when: false
  sudo: yes
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  with_items: karaf_features
  tags:
    - install-features

- name: "Install feature: Check features install"
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:list -i --no-format | grep {{ item.name }}\\\s+{{ item.version }}" >>/tmp/feature.txt'
  changed_when: false
  sudo: yes
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  with_items: karaf_features
  tags:
    - install-features

- name: "Install feature: Cat feature.txt"
  shell: cat /tmp/feature.txt
  changed_when: false
  register: karaf_find_feature_to_update
  tags:
    - install-features

- name: "Install feature: Update features"
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:{{ karaf_command_install_or_upgreade }} {{ item.name }}/{{ item.version }}"'
  sudo: yes
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  when: not karaf_find_feature_to_update.stdout|search("{{item.name}}\\s*{{item.version}}")
  with_items: karaf_features
  register: karaf_new_feature_update
  tags:
    - install-features

- name: "Install feature: Delete feature.txt"
  file:
    path: /tmp/feature.txt
    state: absent
  sudo: yes
  changed_when: false
  tags:
    - install-features

- name: "Pause until you can verify updates to an application were successful."
  pause:
    seconds: '10'
  sudo: yes
  when: karaf_pause_update_features == "yes"

- name: "Install feature: Restart Karaf"
  action: shell echo "Restart Karaf"
  notify: Karaf configuration changed
  when: item.restart_karaf == "yes" and karaf_new_feature_update.changed
  with_items: karaf_features
  sudo: yes
  tags:
    - install-features
