---

- name: "Install features: Find the full features install list with versions"
  set_fact:
    full_features_install_list_with_versions: '{% for features in karaf_features %}{{ features.name }}/{{ features.version }} {% endfor %}'

- name: "Install features: Find the full features install list without versions"
  set_fact:
    full_features_install_list_without_versions: '{{ full_features_install_list_with_versions | regex_replace("(/\S+)\s", "|") | regex_replace("(^.*)(.$)", "\1") }}'

- name: "Install features: Preparation the full features install list for grep"
  set_fact:
    full_features_install_list_for_grep: "feature:list -i --no-format | grep '^({{ full_features_install_list_without_versions }})\\s'"

- name: "Install features: Clean cache"
  sudo: yes
  file:
    path: '{{karaf_home }}/data/clean_cache'
    state: touch
    mode: 0755
  register: karaf_cache_cleaned
  when: karaf_clean_cache == "yes"
  tags:
    - install-features

- name: "Install features: Restart Karaf for Clean cache"
  sudo: yes
  service:
    name: '{{ karaf_service_link_name }}'
    state: restarted
  when: karaf_cache_cleaned.changed
  tags:
    - install-features

- name: "Install features: Wait for Karaf to start"
  wait_for: "port={{ karaf_ssh_port }} timeout=30"
  tags:
    - install-features

- name: "Install features: Add features configs"
  sudo: yes
  template:
    src: "{{ karaf_path_features_configs }}{{ '/' ~ karaf_environment_configs if karaf_environment_configs is defined else '' }}/{{ item.1 }}"
    dest: '{{ karaf_home }}/etc/{{ item.1 | regex_replace(".j2", "") }}'
    owner: "{{ karaf_os_user_name }}"
    group: "{{ karaf_os_user_name }}"
    mode: 0644
    backup: yes
  with_subelements:
    - karaf_features
    - conf_files
  tags:
    - install-features

- name: "Install features: Add external data source"
  sudo: yes
  template:
    src: "{{ karaf_path_features_configs }}{{ '/' ~ karaf_environment_configs if karaf_environment_configs is defined else '' }}/{{ item.1 }}"
    dest: '{{ karaf_home }}/deploy/{{ item.1 | regex_replace(".j2", "") }}'
    owner: "{{ karaf_os_user_name }}"
    group: "{{ karaf_os_user_name }}"
    mode: 0644
    backup: yes
  with_subelements:
    - karaf_features
    - data_source_files
  tags:
    - install-features

- name: "Install features: Add features repositories"
  sudo: yes
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "feature:repo-add {% if item.url|d() %} {{ item.url }} {% else %} {{ item.repo }} {{ item.version }} {% endif %}"'
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  with_items: karaf_features
  when: item.url is defined or item.repo is defined
  changed_when: false
  tags:
    - install-features

- name: "Install features: Perform a simulation"
  sudo: yes
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "feature:install -t -v {{ full_features_install_list_with_versions }}"'
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  register: karaf_new_feature_install
  changed_when: false
  tags:
    - install-features

- name: "Install features: has features pending changes"
  set_fact:
    karaf_has_features_pending_changes: not karaf_new_feature_install.stdout|search("No deployment change")

- name: "Install features: Check features install"
  sudo: yes
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ full_features_install_list_for_grep }}" >/tmp/feature.txt'
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  when: karaf_has_features_pending_changes
  changed_when: false
  tags:
    - install-features

- name: "Replace features in the file feature.txt"
  replace:
    dest: "/tmp/feature.txt"
    regexp: '(?m)^(\S+)\s+(\S+)(.*)'
    replace: '\1/\2'
  when: karaf_has_features_pending_changes
  changed_when: false
  tags:
    - install-features

- name: "Preparation features list for uninstall"
  lineinfile:
    dest: "/tmp/feature.txt"
    regexp: '{{ item.name }}/{{ item.version }}'
    state: absent
  with_items: karaf_features
  when: karaf_has_features_pending_changes
  changed_when: false
  tags:
    - install-features

- name: "Get features list for uninstall"
  shell: 'cat /tmp/feature.txt'
  register: karaf_find_feature_to_uninstall
  when: karaf_has_features_pending_changes
  changed_when: false
  tags:
    - install-features

- name: "Install features: Clean cache on upgrade"
  sudo: yes
  file:
    path: '{{karaf_home }}/data/clean_cache'
    state: touch
    mode: 0755
  register: karaf_cache_cleaned_on_upgrade
  with_items: karaf_features
  when: ((karaf_has_features_pending_changes and karaf_find_feature_to_uninstall.stdout is defined and
         karaf_find_feature_to_uninstall.stdout != "" and karaf_find_feature_to_uninstall.stdout|search(item.name) and
          item.karaf_clean_cache_on_upgrade is defined and item.karaf_clean_cache_on_upgrade == "yes") and
           (karaf_cache_cleaned is not defined or not karaf_cache_cleaned.changed))
  tags:
    - install-features

- name: "Install features: Restart Karaf for Clean cache on upgrade"
  sudo: yes
  service:
    name: '{{ karaf_service_link_name }}'
    state: restarted
  when: karaf_cache_cleaned_on_upgrade.changed
  tags:
    - install-features

- name: "Install features: Wait for Karaf to start on upgrade"
  wait_for: "port={{ karaf_ssh_port }} timeout=30"
  when: karaf_cache_cleaned_on_upgrade.changed
  tags:
    - install-features

- name: "Install features: Add features url for Clean cache on upgrade"
  sudo: yes
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "feature:repo-add {% if item.url|d() %} {{ item.url }} {% else %} {{ item.repo }} {{ item.version }} {% endif %}"'
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  with_items: karaf_features
  when: (karaf_cache_cleaned_on_upgrade.changed and (item.url is defined or item.repo is defined))
  changed_when: false
  tags:
    - install-features

- name: "Install features: Install features"
  sudo: yes
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "feature:install --upgrade {{ full_features_install_list_with_versions }}"'
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  when: karaf_has_features_pending_changes
  tags:
    - install-features

- name: "Pause for Install features"
  pause:
    seconds: '5'
  when: karaf_has_features_pending_changes
  tags:
    - install-features

- name: "Install features: Wait Services"
  sudo: yes
  shell: '{{ karaf_connect_to_local_Karaf_instance }} "service:wait -e -t {{ karaf_timeout_to_wait_service }} {{ item.wait_service }}"'
  sudo_user: "{{ karaf_os_user_name }}"
  environment:
    JAVA_HOME: "{{ karaf_java_home }}"
  when: '{{ item.wait_service is defined and karaf_has_features_pending_changes }}'
  with_items: karaf_features
  tags:
    - install-features

- name: "Install feature: Restart Karaf"
  sudo: yes
  action: shell echo "Restart Karaf"
  notify: Karaf configuration changed
  with_items: karaf_features
  when: ((karaf_has_features_pending_changes and karaf_find_feature_to_uninstall.stdout is defined and
         karaf_find_feature_to_uninstall.stdout != "" and karaf_find_feature_to_uninstall.stdout|search(item.name) and
          item.karaf_restart_on_upgrade is defined and item.karaf_restart_on_upgrade == "yes") or
           (karaf_has_features_pending_changes and karaf_find_feature_to_uninstall.stdout is defined and
            karaf_find_feature_to_uninstall.stdout == "" and item.karaf_restart_on_upgrade is defined and
             item.karaf_restart_on_upgrade == "yes"))
  tags:
    - install-features
