---

- include: "install.yml"
- include: "configure-wrapper.yml"
- include: "configure-karaf.yml"

- include: "delete-data.yml"
  when: karaf_delete_data == "yes"

# Install upgrade function
- include: "add-upgrade-function.yml"
  when:  karaf_features and karaf_command_install_or_upgreade == 'upgrade'

- include: "upgrade-features.yml"
  when: karaf_features and karaf_command_install_or_upgreade == 'upgrade'

- include: "install-features.yml"
  when: karaf_features and karaf_command_install_or_upgreade == 'install'
