---

- include: "install.yml"
- include: "configure-wrapper.yml"
- include: "configure-karaf.yml"

- include: "delete-data.yml"
  when: karaf_delete_data == "yes"

- include: "install-features.yml"
  when: karaf_features and karaf_command_install_or_upgreade == 'install'

- include: "upgrade-features.yml"
  when: karaf_features and karaf_command_install_or_upgreade == 'upgrade'