---

- include: "install.yml"
- include: "configure-wrapper.yml"
- include: "configure-karaf.yml"

- include: "delete-data.yml"
  when: karaf_clean_all == "yes"

- include: "install-features.yml"
  when: karaf_features
