---
#
#- name: "Add features configs"
#  copy:
#    src: 'features-configs/{{ item }}'
#    dest: '{{ karaf_home }}/etc'
#    owner: "{{ karaf_os_user_name }}"
#    mode: 644
#    backup: yes
#  with_items: conf_files
#  sudo: yes
#  tags:
#   - features
#
#- name: "Add features url"
#  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:{{ karaf_command_prefix_refresh }} {{ url }}/{{ version }}/xml/features"'
#  changed_when: false
#  sudo: yes
#  sudo_user: "{{ karaf_os_user_name }}"
#  environment:
#    JAVA_HOME: "{{ karaf_java_home }}"
#  tags:
#   - features
#
#- name: "Check features install"
#  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:list -i --no-format | grep {{ name }}\\\s+{{ version }}" >/tmp/feature.txt'
#  sudo: yes
#  environment:
#    JAVA_HOME: "{{ karaf_java_home }}"
#  tags:
#   - features
#
#- name: "Check feature.txt Empty or not Empty"
#  stat:
#    path: /tmp/feature.txt
#  register: karaf_new_feature_update
#  tags:
#    - features
#
#- name: "Update features"
##  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:install {{ name }}{{ "/" ~ version if install_version == "yes" else "" }}"'
#  shell: '{{ karaf_connect_to_local_Karaf_instance }} "{{ karaf_command_prefix_feature }}:install {{ name }}/{{ version }}"'
#  sudo: yes
#  sudo_user: "{{ karaf_os_user_name }}"
#  environment:
#    JAVA_HOME: "{{ karaf_java_home }}"
#  when: karaf_new_feature_update.stat.size == 0
#  tags:
#   - features
#
#- name: "Restart Karaf"
#  action: shell echo "Restart Karaf"
#  when: restart_karaf == "yes"
#  notify: Karaf configuration changed
#  sudo: yes
#  tags:
#   - features
