---

- name: "Karaf configuration changed"
  service:
    name: '{{ karaf_service_name }}'
    state: restarted
  become: yes
  when: karaf_clean_cache == 'no' and karaf_clean_all == 'no'
            and karaf_restart_on_install_jcp is defined and not karaf_restart_on_install_jcp.changed
            and karaf_restart_on_feature_upgrade is defined and not karaf_restart_on_feature_upgrade.changed
