---

- name: "Karaf clean cache"
  become: yes
  file:
    path: '{{karaf_home }}/data/clean_cache'
    state: touch
    mode: 0755
  when: karaf_clean_data == 'no' or karaf_delete_all == "no"
  notify: Karaf restart

- name: "Karaf restart"
  become: yes
  service:
    name: '{{ karaf_service_name }}'
    state: restarted
